version: '3'

services:
  db:
    image: postgres:14.3
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${GUITARDB}
    container_name: guitardb
    volumes:
      - ./postgresql:/var/lib/postgresql/data
